version: '3.8'
services:
  db:
    image: postgres:16
    container_name: testify-postgres
    environment:
      POSTGRES_USER: testifyuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: testifydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: